[package]
name = "northern-lines-ais-route-mapper"
version = "0.1.0"
description = "Northern Lines AIS Route Mapper"
authors = ["Northern Lines"]
edition = "2021"

[lib]
name = "northern_lines_ais_route_mapper_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
