import React from 'react';
import { EditorialContent } from '../project/nlroute';

type Props={value:EditorialContent;onChange:(next:EditorialContent)=>void};
export const EditorialContentEditor:React.FC<Props>=({value,onChange})=>{
 const setJourney=(key:'eyebrow'|'title'|'description',text:string)=>onChange({...value,journey:{...value.journey,[key]:text}});
 const updatePlace=(id:string,key:'name'|'description',text:string)=>onChange({...value,places:value.places.map(p=>p.id===id?{...p,[key]:text}:p)});
 const removePlace=(id:string)=>onChange({...value,places:value.places.filter(p=>p.id!==id)});
 const addPlace=()=>{const name=window.prompt('Name des Reiseortes');if(!name)return;const lat=Number(window.prompt('Breitengrad'));const lon=Number(window.prompt('Längengrad'));if(!Number.isFinite(lat)||!Number.isFinite(lon))return;onChange({...value,places:[...value.places,{id:`place-${Date.now()}`,name,description:'',anchor:{lat,lon},labelOffset:{x:18,y:-18},visible:true}]});};
 return <aside className="nl-panel rounded-2xl p-4 shadow-sm space-y-5">
  <div><div className="text-[10px] uppercase tracking-[.18em] text-[#6f7c68] font-semibold">Editorial</div><div className="mt-1 text-sm font-semibold text-[#24302e]">Reise & Orte</div></div>
  <div className="space-y-2"><input value={value.journey.eyebrow} onChange={e=>setJourney('eyebrow',e.target.value)} placeholder="Region · z. B. NORWEGEN" className="w-full rounded-lg border border-[#d8d2c5] bg-[#fffdf8] px-3 py-2 text-xs"/><input value={value.journey.title} onChange={e=>setJourney('title',e.target.value)} placeholder="Titel der Reise" className="w-full rounded-lg border border-[#d8d2c5] bg-[#fffdf8] px-3 py-2 text-sm font-semibold"/><textarea value={value.journey.description} onChange={e=>setJourney('description',e.target.value)} placeholder="Kurze Beschreibung der Reise" rows={4} className="w-full resize-none rounded-lg border border-[#d8d2c5] bg-[#fffdf8] px-3 py-2 text-xs leading-relaxed"/></div>
  <div className="border-t border-[#ddd6c9] pt-4"><div className="flex items-center justify-between mb-3"><span className="text-[10px] uppercase tracking-[.16em] text-[#6f7c68] font-semibold">Reiseorte</span><button onClick={addPlace} className="nl-button rounded-full px-2.5 py-1 text-[10px]">+ Ort</button></div><div className="space-y-3">{value.places.length===0&&<p className="text-[11px] leading-relaxed text-[#7a827d]">Noch keine Reiseorte angelegt. Orte werden redaktionell kuratiert und nicht automatisch auf die Karte geklatscht.</p>}{value.places.map(p=><div key={p.id} className="rounded-xl border border-[#ddd6c9] bg-[#f7f4ec] p-3"><input value={p.name} onChange={e=>updatePlace(p.id,'name',e.target.value)} className="w-full bg-transparent text-xs font-semibold text-[#24302e] outline-none"/><textarea value={p.description} onChange={e=>updatePlace(p.id,'description',e.target.value)} placeholder="optionaler redaktioneller Zusatz" rows={2} className="mt-1 w-full resize-none bg-transparent text-[11px] leading-relaxed text-[#66716d] outline-none"/><button onClick={()=>removePlace(p.id)} className="mt-1 text-[10px] text-[#9a7749]">Entfernen</button></div>)}</div></div>
 </aside>;
};
