import React,{useEffect,useMemo,useState}from'react';
import{VoyageData}from'../types';
import{EditorialContent,GapDisplayAdjustment}from'../project/nlroute';
import{buildEditorialJourneyLines}from'../cartography/journeyGeometry';
import{buildGeographicScene}from'../cartography/naturalEarth';
import{GeographicScene}from'../cartography/types';
import{composeJourney}from'../cartography/composition';
interface Props{voyage:VoyageData;gapAdjustments:GapDisplayAdjustment[];editorial:EditorialContent}
export const EditorialMapPreview:React.FC<Props>=({voyage,gapAdjustments,editorial})=>{const[scene,setScene]=useState<GeographicScene|null>(null);const journeyLines=useMemo(()=>buildEditorialJourneyLines(voyage,gapAdjustments),[voyage,gapAdjustments]);const composition=useMemo(()=>composeJourney(voyage.bounds),[voyage.bounds]);useEffect(()=>{let c=false;const f=composition.journeyField;buildGeographicScene(voyage.bounds,journeyLines,f.width,f.height).then(n=>{if(!c)setScene(n)});return()=>{c=true}},[voyage.bounds,journeyLines,composition]);return <section className="nl-panel rounded-2xl p-4 shadow-sm"><div className="mb-3 px-1"><div className="text-[10px] uppercase tracking-[.18em] text-[#6f7c68] font-semibold">005B-D · Typography & Journey Places</div><div className="mt-1 text-sm font-semibold text-[#24302e]">Editorial Map · Northern Lines Preview</div></div><div className="rounded-xl border border-[#d8d2c5] bg-[#ebe6da] p-3 flex justify-center min-h-[420px]">{!scene?<div className="m-auto text-xs text-[#66716d]">Editoriale Karte wird aufgebaut …</div>:<svg viewBox={`0 0 ${composition.width} ${composition.height}`} className="h-[68vh] max-h-[820px] w-auto max-w-full bg-[#f7f4ec]"><rect width={composition.width} height={composition.height} fill="#f7f4ec"/><g fontFamily="Avenir Next,Avenir,sans-serif"><text x="58" y="48" fontSize="12" letterSpacing="4" fill="#6f7c68">{editorial.journey.eyebrow.toUpperCase()}</text><text x="56" y="88" fontSize="31" fill="#24302e" fontWeight="600">{editorial.journey.title||voyage.metadata.title}</text><text x="58" y="116" fontSize="13" fill="#66716d">{editorial.journey.description.slice(0,100)}</text></g><g transform={`translate(${composition.journeyField.x} ${composition.journeyField.y})`}><g fill="#e9e4d8" stroke="#c8c1b3">{scene.landPaths.map((p,i)=><path key={i} d={p} fillRule="evenodd"/>)}</g><g fill="none" stroke="#31575d" strokeWidth="5.2">{scene.journeyPaths.map((p,i)=><path key={i} d={p}/>)}</g></g><g fontFamily="Avenir Next,Avenir,sans-serif" fill="#66716d"><text x="58" y={composition.height-55} fontSize="11" letterSpacing="2">{editorial.places.filter(p=>p.visible).map(p=>p.name).join(' · ')}</text><text x="58" y={composition.height-29} fontSize="11">{voyage.metadata.vesselName}</text></g></svg>}</div></section>};
